### ISSUE TITLE
Get rendered markdown

### ISSUE THREAD

**Issue by bramvanderholst** [GraphCMS/Issue-tracker#11]
Hi there! Great product, loving it so far!

Small issue we're running into, we're trying to migrate our current blog and some posts are written in markdown. So the markdown field was a no-brainer, but it seems that it only offers an interface in the backend. Is it maybe possible to have a `$fieldname_rendered` for each markdown field as well, or maybe an argument to the field `myField ($asHtml Boolean)`?

**Comment by mlukaszczyk** [comment]
Hey Bram, thanks for the kind words! But could you please elaborate on your issue? So I guess you want your markdown delivered parsed as HTML? I would actually recommend to stick with the markdown from the backend and use a markdown interpreter on the frontend.

**Comment by mlukaszczyk** [comment]
Hey @bramvanderholst, did you find a solution for this issue? Did my answer help?

**Comment by bramvanderholst** [comment]
Hi @mlukaszczyk, even though I would've liked to have seen an option for parsed markdown, I can indeed use an interpreter on the frontend. The problem with that is, it requires you to add an interpreter lib in the frontend which is extra (potentially unnecessary) kb's. But seeing as the marked lib is only about 19kb minified, I guess it's fine!

Thanks! :)

**Comment by mlukaszczyk** [comment]
I will put this feature request in our internal backlog and let you know if we can offer a proper solution for this (:
