### ISSUE TITLE
Issue where adding a field disables all inputs afterwards

### ISSUE THREAD

**Issue by LiamMartens** [GraphCMS/Issue-tracker#13]
When I add a field the inputs never re-enable again for some reason which means I have to refresh the page to add another field

![mar-29-2017 12-40-30](https://cloud.githubusercontent.com/assets/5265324/24450925/195389ee-147d-11e7-8bde-f1d69a92f2b3.gif)

**Comment by d-winter** [comment]
Hey @LiamMartens, thanks for reporting.
I fixed it and released a new version of the app.
