### ISSUE TITLE
[UI] Row visuals remaining after deletion

### ISSUE THREAD

**Issue by LiamMartens** [GraphCMS/Issue-tracker#14]
Might again be just me xD
![mar-30-2017 00-27-00](https://cloud.githubusercontent.com/assets/5265324/24479451/b1cf999e-14df-11e7-821e-5894c4a7f5af.gif)

**Comment by mlukaszczyk** [comment]
No, its not just you (: it´s a known issue for us but was on low prio. Will take a look.

**Comment by LiamMartens** [comment]
You can keep it on low priority but you know me, stuff like that bug me ;)

**Comment by mlukaszczyk** [comment]
Totally understand this ;)

**Comment by d-winter** [comment]
Hey @LiamMartens 
can you check again? This seems to be fixed by some refactorings of the table view.
I cannot reproduce it on my machine. Feel free to close this issue if it's also gone on you app.

**Comment by LiamMartens** [comment]
Can confirm fixed
