### ISSUE TITLE
SVG thumbnail

### ISSUE THREAD

**Issue by LiamMartens** [GraphCMS/Issue-tracker#15]
![Thumbnail](https://cloud.githubusercontent.com/assets/5265324/24830123/f52a8f3a-1c7f-11e7-9834-8716545851bc.png)

Can't say it works quite as desired. With vectors the thumbnail should really just show the vector itself imo.

What you see there is just the border of the vector

**Comment by mlukaszczyk** [comment]
That looks unintended, but should be no problem to solve. Thanks for reporting!

**Comment by d-winter** [comment]
Hey @LiamMartens 
This is fixed now.
Thanks again for reporting.
