### ISSUE TITLE
Cannot create new projects

### ISSUE THREAD

**Issue by bnhovde** [GraphCMS/Issue-tracker#16]
When creating a new project (New account) I get the following error:

 > Error creating project: Server request for mutation `createProjectMutation` failed for the following reasons: 1. A synchronous mutation callback failed eateProjectInput!)(createProject(input:$input_0) {clientMut ^^^

I've tried creating another account (Sign in with Google), but same error.

On refresh, the project is there, but when I open it the browser crashes.

**Comment by d-winter** [comment]
Hi @bnhovde,
this issue is fixed. Please just ignore your broken projects. I will take a deeper look at those and clean them up later.
Sorry for this issue!
