### ISSUE TITLE
Can not edit relation field.

### ISSUE THREAD

**Issue by paales** [GraphCMS/Issue-tracker#18]
It doesn't seem possible to edit a relation field of an object, clicking the pencil icon doesn't do anything. 

http://cloud.h-o.nl/lNGg

**Comment by mlukaszczyk** [comment]
Hey @paales, we will roll out a large backend redesign in the next week, which will allow this operation. Our current API wasn't stable on this operation so we disabled it temporarily. The update will be quiet large and also introduce the field based permissions. We will also release a blog post on what will change. Project instances and APIs won't be touched. This only affects the web app.

**Comment by paales** [comment]
Cool, thanks!

**Comment by benjamingeorge** [comment]
Has any progress on this happened ?  I'm trying to create hierarchical Models something like like "Pages" in wordpress.  A Page can have one parent, and many child pages.

**Comment by mlukaszczyk** [comment]
Hey @benjamingeorge, this feature (like matrix fields in craft) will soon be scheduled! Sorry for the delay but our backend redesign has set us back by almost two months. For now I will close this issue as it is about editing relations, which is now working.
