### ISSUE TITLE
[UI] SVG icon files aren't always fitting

### ISSUE THREAD

**Issue by LiamMartens** [GraphCMS/Issue-tracker#19]
![deepinscreenshot20170630113925](https://user-images.githubusercontent.com/5265324/27730224-d29792b6-5d88-11e7-8355-6aead82c3ad5.png)

**Suggested fix**
Add `max-width: 100%` to the `img` tags

**Comment by mlukaszczyk** [comment]
Thanks for reporting!

**Comment by mlukaszczyk** [comment]
Fixed in the next release.
