### ISSUE TITLE
[UI] Wide table double overflow

### ISSUE THREAD

**Issue by LiamMartens** [GraphCMS/Issue-tracker#20]
![deepinscreenshot20170630114254](https://user-images.githubusercontent.com/5265324/27730376-49bbdb04-5d89-11e7-9670-59fcec5536a6.png)$

`min-width` on `.bodyScrollWrapper` is too small causing double overflow scroll bars

**Comment by mlukaszczyk** [comment]
Hm thought I fixed the issue. Will take a look! Sorry for the delay in resolving the old issues, but as mentioned we prepare a larger release.
