### ISSUE TITLE
Uploading asset during new entry resets form

### ISSUE THREAD

**Issue by LiamMartens** [GraphCMS/Issue-tracker#22]
When creating a new entry in a model which accepts media and you upload a file from the new entry screen the form resets.

**As can be seen below**
![screencap](https://user-images.githubusercontent.com/5265324/28642490-dabeaf90-7252-11e7-9d65-3ef009c69675.gif)

**Comment by mlukaszczyk** [comment]
Hey Liam thanks for reporting! This issue is already known and we hope to have it fixed by the end of this week.

**Comment by mlukaszczyk** [comment]
fixed
