### ISSUE TITLE
Multiline textarea jumps cursor upon resizing

### ISSUE THREAD

**Issue by LiamMartens** [GraphCMS/Issue-tracker#23]
Title is self explanatory, issue can be seen below
![deepin-screen-recorder_select area_20170728130323](https://user-images.githubusercontent.com/5265324/28714761-3036da68-7395-11e7-883f-115bb2c0b433.gif)

Probably need to re-set the cursor position using the `setSelectionRange` method.

**Comment by mlukaszczyk** [comment]
Oh that's odd. We will have closer look at this!

**Comment by dmak78** [comment]
Also experiencing this issue.

**Comment by lethalwebapps** [comment]
Hey @LiamMartens thanks for reporting.
This is an issue caused by a bug in react  with controlled inputs.
I have added a fix for it and will release it later this day.

**Comment by d-winter** [comment]
Hi @LiamMartens,
this was a bug in material-ui and is fixed and live now.
Thanks for reporting!
