### ISSUE TITLE
Clicking a relation entry does not bring up editor

### ISSUE THREAD

**Issue by LiamMartens** [GraphCMS/Issue-tracker#25]
I believe this should be possible for ease of use, but also it has the pointer cursor meaning it should be clickable and do something but it doesn't.

![deepin-screen-recorder_select area_20170728235617](https://user-images.githubusercontent.com/5265324/28737799-84e8d1be-73f0-11e7-8468-6dc7e8308d6a.gif)

**Comment by mlukaszczyk** [comment]
Hey Liam, in the coming weeks we'll introduce an inline editing view that will also allow to create new related objects on the fly.
