### ISSUE TITLE
[UI] API Hints remains across other pages

### ISSUE THREAD

**Issue by tgfjt** [GraphCMS/Issue-tracker#26]
![graphcms-hints](https://user-images.githubusercontent.com/2628239/29488439-2d4eb36c-8546-11e7-95cb-179aaf967653.gif)

**Comment by mlukaszczyk** [comment]
Yeah that's an annoying GraphiQL bug. We will soon bump the version on this so chances are that this is already fixed. Otherwise I'm sure we can write a quick fix for this.
