### ISSUE TITLE
[UI] too hard to show a Panel on the bottom

### ISSUE THREAD

**Issue by tgfjt** [GraphCMS/Issue-tracker#27]
once hide the panel, the toggle button is hidden by intercom Launcher. 👅

![image](https://user-images.githubusercontent.com/2628239/29712439-ce547e76-89d4-11e7-8425-63dbd88ecf6f.png)

**Comment by mlukaszczyk** [comment]
Well that's just annoying! We already made a feature request to make this widget dismissable but we will just do it on our own.

**Comment by tgfjt** [comment]
Thanks!

**Comment by krawaller** [comment]
Bump for this issue, this is still a thing! Sure it is easy enough to nuke the widget in the dev tools, but it really doesn't give a good first impression of the quality of the GUI.

How about just adding some padding to the bottom of `.entryForm`?

![image](https://user-images.githubusercontent.com/249764/32056091-08451914-ba64-11e7-824d-1dfe8845d2aa.png)

**Comment by mlukaszczyk** [comment]
Will fix it this week!

**Comment by d-winter** [comment]
This is fixed now. Sorry for the delay

**Comment by tgfjt** [comment]
Congrats!
