### ISSUE TITLE
line-break in Code Block multiplied after saved...

### ISSUE THREAD

**Issue by tgfjt** [GraphCMS/Issue-tracker#28]
Save this.

![image](https://user-images.githubusercontent.com/2628239/29715270-947ff470-89e1-11e7-96d8-2c86b08596e1.png)

Then save.

![image](https://user-images.githubusercontent.com/2628239/29715289-a5ed743a-89e1-11e7-90c1-5bea2441c88c.png)

Uh-oh.

![image](https://user-images.githubusercontent.com/2628239/29715309-cea6b81e-89e1-11e7-9231-3b37975f18aa.png)

**Comment by mlukaszczyk** [comment]
Thanks for reporting! This shouldn't be and we are aware that the editors are not super comfortable. We will soon redesign them completely.

**Comment by flexzuu** [comment]
Hey i just deployed a quick fix. I introduces some new minor issue. (If you use breaks to position text it will reset it to a sane html structure after editing). 
But we think to fix this bug is more important for the time being. For the future we plan on a redesign of the Text Input types.
