### ISSUE TITLE
Can't upload assets. Button doesn't do anything.

### ISSUE THREAD

**Issue by johhansantana** [GraphCMS/Issue-tracker#29]
When trying to upload assets on any given page that lets you click on the `upload` button, nothing really happens using google chrome (not sure about other browsers).

![img](https://user-images.githubusercontent.com/9933887/29755461-2437b492-8b66-11e7-902e-a542ede026e0.gif)

**Comment by mlukaszczyk** [comment]
Hey @johhansantana, that is odd. Are you using the regular Chrome or some alternative release? Your project is in a functional state. Can you please check if you see something in the JS console?

I tested on the latest Chrome and everything is working for me. Also, what OS are you using?

**Comment by johhansantana** [comment]
🤔 this is weird, it tried it again today and it works :l I think it may have been something with my internet since from the looks of it, it seems that it was trying to download the dynamic component when you press the button and since the internet wasn't behaving maybe it was taking longer for it to download?

Anyways, great platform! Hopefully I'll use it soon on a real project :D

**Comment by mlukaszczyk** [comment]
Yeah, sounds a little odd (: 

Happy it works now! Thanks a lot.
