### ISSUE TITLE
[UI] Field description in Model view gets cut off if too long.

### ISSUE THREAD

**Issue by rafaelderolez** [GraphCMS/Issue-tracker#31]
The field description has a max-width of 500px and gets cut off.

```
.model .infoRow .topLine .description {
    …
    max-width: 500px;
    …
}
```

![screen shot 2017-10-04 at 12 18 34](https://user-images.githubusercontent.com/6158959/31170953-61114544-a8fe-11e7-9d74-086e0b2409f4.png)

**Comment by belazer** [comment]
UI fixes will be addressed in the new web app!
