### ISSUE TITLE
Broken link in documentation

### ISSUE THREAD

**Issue by tremby** [GraphCMS/Issue-tracker#34]
On the [concepts page](https://graphcms.com/docs/Concepts/):

> As an alternative, you can set up public access for create, read, update and delete operations ([see here](https://graphcms.com/docs/guides/Public_API_access)). This will allow you to skip the token step.

The link is broken. I have a feeling the docs here are also out of date, or they're at least confusing.

**Comment by mlukaszczyk** [comment]
Thanks! Yes they are. The good thing is that we are already working on fixing them. A lot of stuff is out dated!
