### ISSUE TITLE
separation of content and page schemas

### ISSUE THREAD

**Issue by dohomi** [GraphCMS/Issue-tracker#4]
Hey

inside of a CMS I would like to see a separation of content element structures and page elements (currently named as content).

Content elements should be visible while adding content to a page structure and should behave like widgets. 

In the real world I would address maybe 3-4 page types: 
```
1. page
2. blog
3. news
4. product
```

Inside of each of this "page" type I would like to see an array, sortable inside each page type, which consists of various content elements (widgets). A widget would be something like:
``` 
1. slider
2. 3/3/4 column element
3. head/subhead/image widget
4. tabs
5. accordion
(...)
```

I think it would be great to give users the ability to define these widgets and assign them in a predefined place inside of the page types.

Hope this make sense to you guys

Cheers

**Comment by mlukaszczyk** [comment]
@dohomi I think I have an Idea of what your feature request is about, but I also think that this concerns presentation and this is not what a headless CMS should be concerned about. This is usually something that you would tailor in a template and not within your content API. Anyways, maybe we should schedule a call so we could elaborate a a little bit more on how we could get the best out of both worlds here.

**Comment by mlukaszczyk** [comment]
Hey @dohomi, took a little but we think that we found a decent solution for this. Currently we are in a backend redesign, but after this we are going to schedule this feature.

**Comment by dohomi** [comment]
@mlukaszczyk great to hear!

**Comment by mlukaszczyk** [comment]
Sorry for taking so long here. The feature still hasn't landed as we are currently redesigning our complete stack. We have sketched two possible solutions for this, one would require union types, which currently aren't supported by Prisma. This is still on our list but there is currently no ETA.
