### ISSUE TITLE
When creating a new item its hard to cancel

### ISSUE THREAD

**Issue by toshi38** [GraphCMS/Issue-tracker#54]
If you're adding a new item to a model, its really hard to cancel, you have to navigate away?

**Comment by belazer** [comment]
Could you elaborate a bit more on this one?

**Comment by toshi38** [comment]
Slacked you a video... 

But for completeness, if you click + from the left hand menu to create a new entry, there doesn't appear any to be any way to cancel?  You can navigate away... but theres no "cancel" or "x" button that I see?
