### ISSUE TITLE
records in GUI occasionally fail to save

### ISSUE THREAD

**Issue by brandonmp** [GraphCMS/Issue-tracker#56]
Chrome 62 / win10

I'm not sure what triggered this bug so I'll just recap what I did prior to seeing it:

1. I created a new model of type `School` with a 1:many connection to a type `Blurb`.

2. Created a single `School` & created/connected some `Blurb`s, publishing everything.

3. Added an asset field, `logo` to `School`.

4. Uploaded / connected an asset to the record I made in step 2.

5. Clicked save.

I then got this error alert, with no save occurring:

![image](https://user-images.githubusercontent.com/14139991/32996349-80cbf788-cd4f-11e7-95e8-c49aca81c8bb.png)

6. I then refreshed the page, but all of my `Blurb` connections appeared to be gone. 

7. I confirmed on the `Blurb` end of the connection that it was still intact, then went back to the `School` type.

8. The `School` I had made wasn't showing up, though the counter in the sidebar still showed a '1.' There was some error about blurbId that I wasn't able to copy (sry). 

9. Some more refreshing, clearing my cache / reset service worker cache etc etc., then finally i was able to save the logo, though this error was in console:

```
Uncaught (in promise) Error: GraphQL error: Cannot query field 'logo' on type 'School'. (line 15, column 5):
    logo {
    ^
    at new t (vendor.3d0650f5838eac04c953.js:48)
    at vendor.3d0650f5838eac04c953.js:69
    at <anonymous>
t @ vendor.3d0650f5838eac04c953.js:48
(anonymous) @ vendor.3d0650f5838eac04c953.js:69
Promise rejected (async)
value @ vendor.3d0650f5838eac04c953.js:69
value @ vendor.3d0650f5838eac04c953.js:69
value @ vendor.3d0650f5838eac04c953.js:69
onClick @ app.3d0650f5838eac04c953.js:1
r.handleTouchTap @ vendor.3d0650f5838eac04c953.js:14
r @ vendor.3d0650f5838eac04c953.js:29
a @ vendor.3d0650f5838eac04c953.js:29
s @ vendor.3d0650f5838eac04c953.js:29
f @ vendor.3d0650f5838eac04c953.js:19
m @ vendor.3d0650f5838eac04c953.js:19
r @ vendor.3d0650f5838eac04c953.js:49
processEventQueue @ vendor.3d0650f5838eac04c953.js:19
r @ vendor.3d0650f5838eac04c953.js:59
handleTopLevel @ vendor.3d0650f5838eac04c953.js:59
o @ vendor.3d0650f5838eac04c953.js:59
perform @ vendor.3d0650f5838eac04c953.js:24
batchedUpdates @ vendor.3d0650f5838eac04c953.js:49
o @ vendor.3d0650f5838eac04c953.js:14
dispatchEvent @ vendor.3d0650f5838eac04c953.js:59
```

I never lost any data (I don't think), but this was a bit of a scary moment! Are there steps I can take w/ the GUI to avoid these kinds of scares / errors?

**Comment by brandonmp** [comment]
hitting new error, now, trying to save/publish new records of type `Blurb`:

![image](https://user-images.githubusercontent.com/14139991/32996626-1ccaf6d6-cd53-11e7-9044-4ce35dbccfb2.png)

**Comment by belazer** [comment]
Same as for #57, I couldn't reproduce your error. Please let me know if the issue still persists or comes up again!
