### ISSUE TITLE
Schema changes between queries, problems ensue

### ISSUE THREAD

**Issue by brandonmp** [GraphCMS/Issue-tracker#57]
to try and fix #56 , i deleted a few models and recreated them, one w/ the same name and one w/ a new name.

This didn't solve the problems in the GUI at all, but it seemed to create some troubling errors in the API too. 

The type I changed the name of went from `School` to `BusinessSchool`. 

What this gif shows is querying `allBusinessSchools`, getting an error that says "did you mean `allSchools`?", then querying `allSchools`, and getting an error that says "Did you mean `allBusinessSchools`?" 

![gcms-school-bug](https://user-images.githubusercontent.com/14139991/32996844-615c501c-cd56-11e7-895e-ce5b0dee4f1a.gif)

Idk what to make of this. When are changes to my schema considered stable? I'm a little worried about this sort of thing happening in production, so I'm hoping it's just due to my editing of the schema in the GUI.

**Comment by brandonmp** [comment]
About 15-20 minutes after I made the schema changes, and it continues to bounce between the old schema and new, preventing me from editing / creating content:

![image](https://user-images.githubusercontent.com/14139991/32996952-9e94b1b2-cd57-11e7-85b0-d6882a90b5d3.png)

**Comment by belazer** [comment]
Hey @brandonmp , thank you for your report! One other user also had issues with his query last night only working 50% of the time. I just tested your query and couldn't see any issues. We suspect this was due to a hiccup from our API provider. Let me know, if the issue still persists.

**Comment by brandonmp** [comment]
awesome thanks @belazer - looks like it's perf'ng pretty stable now so I'll close this out. thx for quick replies here & in chat

**Comment by mlukaszczyk** [comment]
This will be fixed with a new schema deployment mechanism landing in the next large GraphCMS release. A quickfix can be found here: https://github.com/GraphCMS/Issue-tracker/issues/62
