### ISSUE TITLE
Add multiple values on Enter

### ISSUE THREAD

**Issue by rann91** [GraphCMS/Issue-tracker#6]
When creating a new entry, in which you have a field with multiple values, you have to press the "Add to list" button everytime to add a new value. It would be nice if you can just press Enter and the value gets added to the list. Would really speed up the workflow.

<img width="1110" alt="schermafbeelding 2017-02-21 om 09 32 52" src="https://cloud.githubusercontent.com/assets/25922820/23156842/df40e2fe-f818-11e6-8848-bbe4ef1bec39.png">

**Comment by d-winter** [comment]
Hey @rann91 
thanks for reporting. 
I will have a look later this day!

**Comment by d-winter** [comment]
Hey @rann91,
sorry for the delay.
You can now add list field values on enter.
