### ISSUE TITLE
Incorrect unique constraint for emoji

### ISSUE THREAD

**Issue by ttsuruoka** [GraphCMS/Issue-tracker#60]
How to reproduce: 

1. Create a "Text, singleline, Unique" field.
![image](https://user-images.githubusercontent.com/284187/34190125-66aadf04-e582-11e7-8011-d1b34dab8de4.png)

2. Set 🍔 to entry 1. Then set 🍺 to entry 2.

3. Click "Save" button.

Results:
![image](https://user-images.githubusercontent.com/284187/34190131-740705a6-e582-11e7-8366-ffde20f2010b.png)

**Comment by mlukaszczyk** [comment]
We will check if this is still happening in the redesign.
