### ISSUE TITLE
Cannot filter through Enumeration field

### ISSUE THREAD

**Issue by ElisaMassafra** [GraphCMS/Issue-tracker#61]
Hi,
I have added an enumeration field "navigations" (of type Navigations) to my "Page" model but the filter doesn't recognise it. I have a list of enumerations (with multiple values allowed) and when I get allPages the filter by navigations doesn't work.

Here is the schema:

enum Navigations {
  Main
  Footer
}

type Page @model {
  createdAt: DateTime!
  id: ID! @isUnique
  isPublished: Boolean! @defaultValue(value: false)
  navigations: [Navigations!]
  translations: [PageTranslation!]! @relation(name: "PageTranslationRelation")
  updatedAt: DateTime!
}

And here is my query:
query allPages{
  allPages(filter: {navigations: Main}){
    id,
    navigations,
  },
}

The error I get is:
GraphQL error: Argument 'filter' expected type 'PageFilter' but got: {navigations: Main}. Reason: 'navigations' Field 'navigations' is not defined in the input type 'PageFilter'. (line 2, column 20): allPages(filter: {navigations: Main}) { ^ (line 2, column 21): allPages(filter: {navigations: Main}) { ^ GraphQL error: Cannot query field 'navigations' on type 'Page'. Did you mean 'translations'? (line 4, column 5): navigations ^

Any ideas of what is wrong here? It does work for my other queries (I can also filter by locales with no problem).

Thanks

**Comment by belazer** [comment]
Currently it's not possible to filter for lists of enums. The recommended way is to use Relations for this. Our new backend which will be based on Prisma will support that in the future!

**Comment by ElisaMassafra** [comment]
Ok, thanks for the info!
