### ISSUE TITLE
cached permissions producing inconsistent responses

### ISSUE THREAD

**Issue by brandonmp** [GraphCMS/Issue-tracker#62]
this is similar to problems i was hitting in #57 , but it seems different enough to open a new issue.

In #57 , changes to the schema resulted in some portion of queries apparently hitting an old version of the schema, and returning errors. 

Now, I'm hitting the same problem with read permissions. I've created a new model and set permissions to 'read,' but permission seems to be randomly denied. Here's a gif of what I mean. Note that the same query returns either an error, or the results, with no changes to any params.

![graphcms-perms-error](https://user-images.githubusercontent.com/14139991/38157138-01b63f70-3452-11e8-991a-10e5d38319ca.gif)

Note that I the iGraphql is pointing to local host because I am using apollo schema stitching. But the query (and errors) are passed through my server, so there is no interference that might explain this (and my server has no caching configured).

Anything I can do to fix this? Is this a known issue? Will this go away after awhile?

ETA: okay, it seems it's completely the same as the issue in #57. Firing query a few more times results in 'field not available' error:

![image](https://user-images.githubusercontent.com/14139991/38157219-c788270e-3452-11e8-8f50-2e30837a4912.png)

Last time the response was that this was just a hiccup upstream, but it's 5 months later & it's still 'hiccuping' : / please advise

**Comment by mlukaszczyk** [comment]
Hey Brandon, this will be actually fixed by the new GraphCMS release that will come with a new schema deployment mechanism. This happens currently because sometimes the schema isn't synced across API instances. A quick fix is modifying the schema (like changing the description of a text or number field). Please let me know if this helped. Otherwise I will take a closer look at this.

**Comment by mlukaszczyk** [comment]
This will be fixed after the upcoming relaunch 👍
