### ISSUE TITLE
Upload media is not working

### ISSUE THREAD

**Issue by pmadar** [GraphCMS/Issue-tracker#9]
In section media, button UPLOAD do nothing - no reaction on click.
Action 'SHOW_MODAL' in redux dispatched.

**Comment by d-winter** [comment]
Hey @pmadar 
looks like our external file hosting service is currently unavailable. I will check it asap and notify you when you can use image uploads again.
Thanks for reporting!
Daniel

**Comment by d-winter** [comment]
Hmm, looks like its AWS S3's fault:
https://news.ycombinator.com/item?id=13755673

**Comment by mlukaszczyk** [comment]
S3 seems to be up and running again, so media upload is working again (:
